# Generated by Django 2.1a1 on 2018-06-01 05:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comicid', models.AutoField(db_column='comicID', primary_key=True, serialize=False)),
                ('comictitle', models.CharField(blank=True, db_column='comicTitle', max_length=50, null=True)),
                ('comicplot', models.TextField(blank=True, db_column='comicPlot', null=True)),
                ('comicpublisher', models.CharField(blank=True, db_column='comicPublisher', max_length=50, null=True)),
                ('comicseries', models.CharField(blank=True, db_column='comicSeries', max_length=50, null=True)),
                ('comicvolume', models.IntegerField(blank=True, db_column='comicVolume', null=True)),
                ('comicissue', models.IntegerField(blank=True, db_column='comicIssue', null=True)),
                ('comicgenre', models.CharField(blank=True, db_column='comicGenre', max_length=45, null=True)),
                ('comicauthor', models.CharField(blank=True, db_column='comicAuthor', max_length=100, null=True)),
                ('comicsynopsis', models.TextField(blank=True, db_column='comicSynopsis', null=True)),
                ('comicrating', models.IntegerField(blank=True, db_column='comicRating', null=True)),
                ('comiccover', models.CharField(blank=True, db_column='comicCover', max_length=50, null=True)),
            ],
            options={
                'db_table': 'comic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('comicid', models.IntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FavoriteComics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicid', models.IntegerField(null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fav_comic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'following',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 6, 1, 5, 57, 49, 602082, tzinfo=utc))),
                ('post_rating', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('comicid', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('usercity', models.TextField(blank=True)),
                ('profpic', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
    ]
