# Generated by Django 2.0.4 on 2018-05-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': False},
        ),
    ]
