# Generated by Django 2.0.4 on 2018-05-14 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0002_auto_20180512_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userpicture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
