# Generated by Django 2.0.4 on 2018-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0003_auto_20180514_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
