# Generated by Django 2.0.4 on 2018-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0004_auto_20180514_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='media/profile_images'),
        ),
    ]
