# Generated by Django 2.0.4 on 2018-05-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0005_auto_20180514_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profpic',
        ),
    ]
