# Generated by Django 2.0.4 on 2018-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0006_remove_userprofile_profpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
