# Generated by Django 2.0.4 on 2018-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0007_userprofile_profpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usercity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
