# Generated by Django 2.0.4 on 2018-05-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0008_auto_20180514_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
