# Generated by Django 2.0.4 on 2018-05-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0009_auto_20180527_0546'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
