# Generated by Django 2.0.4 on 2018-05-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0010_auto_20180527_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='accountposts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comicusercontent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='favoritecomics',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True},
        ),
    ]
