# Generated by Django 2.0.4 on 2018-05-31 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comicsite', '0011_auto_20180529_0525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountPosts',
        ),
        migrations.DeleteModel(
            name='ComicUserContent',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='favoritecomics',
            name='comicid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comicsite.Comic'),
        ),
        migrations.AddField(
            model_name='favoritecomics',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profpic',
            field=models.FileField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usercity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='favoritecomics',
            table='fav_comic',
        ),
    ]
