# Generated by Django 2.0.4 on 2018-05-31 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comicsite', '0012_auto_20180530_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postcontent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postdate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postrating',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 6, 46, 58, 684089, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritecomics',
            name='comicid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoritecomics',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
