# Generated by Django 2.0.4 on 2018-05-31 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0013_auto_20180530_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 6, 47, 45, 954488, tzinfo=utc)),
        ),
    ]
