# Generated by Django 2.0.4 on 2018-05-31 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0015_auto_20180530_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecomics',
            name='comicid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comicsite.Comic'),
        ),
        migrations.AlterField(
            model_name='favoritecomics',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 17, 18, 53, 537915, tzinfo=utc)),
        ),
    ]
