# Generated by Django 2.0.4 on 2018-05-31 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0021_auto_20180531_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 17, 43, 13, 407863, tzinfo=utc)),
        ),
    ]
