# Generated by Django 2.0.4 on 2018-05-31 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0022_auto_20180531_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecomics',
            name='comicid',
        ),
        migrations.RemoveField(
            model_name='favoritecomics',
            name='userid',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 17, 50, 14, 330749, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='FavoriteComics',
        ),
    ]
