# Generated by Django 2.0.4 on 2018-05-31 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0024_auto_20180531_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecomics',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 18, 33, 33, 50511, tzinfo=utc)),
        ),
    ]
