# Generated by Django 2.0.4 on 2018-05-31 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0026_auto_20180531_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecomics',
            name='fav',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 20, 3, 49, 276337, tzinfo=utc)),
        ),
    ]
