# Generated by Django 2.0.4 on 2018-06-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0030_auto_20180531_1819'),
    ]

    operations = [
    ]
