# Generated by Django 2.0.4 on 2018-06-01 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comicsite', '0031_merge_20180601_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 21, 23, 40, 613639, tzinfo=utc)),
        ),
    ]
